# Generated by Django 5.2.10 on 2026-01-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='id',
            new_name='id_kategori',
        ),
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='nama_kategori',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='harga',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='id',
            new_name='id_produk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='kategori_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='nama_produk',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status',
            new_name='status_id',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='id',
            new_name='id_status',
        ),
        migrations.RenameField(
            model_name='status',
            old_name='name',
            new_name='nama_status',
        ),
    ]
