# Generated by Django 5.2.10 on 2026-01-31 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_id_category_id_kategori_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='kategori_id',
            new_name='kategori',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='status_id',
            new_name='status',
        ),
    ]
